package Nested.Exception;

public class TestThrow1 {

}
